raspberrypi5_vault_tiny_defconfig:
* dropped forgejo on init-lite-vault.sh
* git shell for git user

diff --git a/fs_overlay/fs_vault/root/git-shell-commands/create b/fs_overlay/fs_vault/root/git-shell-commands/create
--- a/fs_overlay/fs_vault/root/git-shell-commands/create
+++ b/fs_overlay/fs_vault/root/git-shell-commands/create
@@ -1,35 +1,24 @@
 #!/bin/sh
+set -eu
 
-# Adapted from: http://planzero.org/blog/2012/10/24/hosting_an_admin-friendly_git_server_with_git-shell
-
-# comment out or adapt if you want to allow non-root users to create new repositories
-# If the user is not root
-#if [ "$USERNAME" != "root" ]
-#then
-  # Display a notice and stop
-#  echo "Sorry, only root can use this command."
-#  exit 1
-#fi
-
-# If no project name is given
-if [ $# -eq 0 ]
-then
-  # Display usage and stop
-  echo "Usage: create <project.git>"
-  exit 1
+if [ "$#" -ne 1 ]; then
+    echo "Usage: create <project.git>" >&2
+    exit 1
 fi
 
-# Set the project name, adding .git if necessary
-extension=".git"
-project=$(echo "$*")
+project=$1
+case "$project" in
+    ''|.*|-*|*[!a-zA-Z0-9._-]*)
+        echo "Invalid project name: use letters, digits, dots, underscores or hyphens; start with a letter or digit." >&2
+        exit 1
+        ;;
+esac
+case "$project" in
+    *.git) ;;
+    *) project="$project.git" ;;
+esac
 
-if [ "${project/$extension}" = "$project" ];
-then
-  project=$project$extension
-fi
-project=$(basename $project)
-# Create and initialize the project
-mkdir /opt/data/git/"$project" && \
-cd /opt/data/git/"$project" && \
-git init --bare --shared 
+cd "$HOME"
+mkdir "$project"
+git init --bare --shared "./$project"
 echo "$project repository created. Check with 'list'"
